import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


// PROVIDER
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import { ThemeProvider } from "@/components/theme/theme-provider"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RewFund Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          footer: "hidden",
        },
      }}
    >
      <html lang="en" suppressHydrationWarning={true}>
        <body className={inter.className} >
            {/* <header>
                <SignedOut>
                  <SignInButton />
                  </SignedOut>
                  <SignedIn>
                  <UserButton />
                  </SignedIn>
            </header> */}
              <main>
                  <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                  >
                    {children}
                  </ThemeProvider>
              </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
